import React from "react";
import { dm_sans } from "@/src/theme/fontConfig";
import RootLayoutProvider from "../hocs/RootLayoutProvider";
import GlobalProvider from "../context/context";
import QueryProvider from "../hocs/QueryProvider";
import GraphqlProvider from "../hocs/GrapqlProvider";

export const metadata = {
  title: "Snipy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <QueryProvider>
          <GraphqlProvider>
            <GlobalProvider>
              <RootLayoutProvider>{children}</RootLayoutProvider>
            </GlobalProvider>
          </GraphqlProvider>
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
