import React from "react";
import { dm_sans } from "@/src/theme/fontConfig";
import RootLayoutProvider from "../hocs/RootLayoutProvider";
import GlobalProvider from "../context/context";

export const metadata = {
  title: "Snipy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <GlobalProvider>
          <RootLayoutProvider>{children}</RootLayoutProvider>
        </GlobalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
